- name: Build and Push Docker Image
  hosts: localhost
  connection: local
  vars:
    image_name: basmaoueslati/compare-appf25
    tag: latest
    docker_registry_url: https://index.docker.io/v1/
  tasks:
    - name: Build Docker image
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ tag }}"
        build:
          path: .
        source: build

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: "{{ docker_registry_url }}"
        username: "docker_username"
        password: "{{docker_password}}"

    - name: Push Docker image
      ansible.builtin.shell: "docker push {{ image_name }}:{{ tag }}"
