- name: Build and Push Docker Image
  hosts: localhost
  connection: local
  vars:
    image_name: basmaoueslati/compare-appf25
    tag: latest
  tasks:
    - name: Build Docker image
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ tag }}"
        build:
          path: .
        source: build

    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "basmaoueslati"
        password: "{{98H230M8rsxsouma}}"

    - name: Push Docker image
      ansible.builtin.shell: "docker push {{ image_name }}:{{ tag }}"
